In [43]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer

In [44]:
df_train = pd.read_csv('data/train.csv')
df_test = pd.read_csv("data/test.csv")

df_test["Transported"] = False
df = pd.concat([df_train, df_test])
df.sample(5)

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
7893,8429_01,Earth,True,G/1351/S,55 Cancri e,23.0,False,0.0,0.0,0.0,0.0,0.0,Briney Donson,True
6333,6699_01,Mars,False,E/429/P,TRAPPIST-1e,13.0,False,0.0,0.0,0.0,0.0,0.0,Powhex Paie,False
3310,7248_01,Mars,False,F/1500/P,55 Cancri e,32.0,False,976.0,0.0,84.0,22.0,0.0,Hony Mité,False
3329,3576_01,Earth,False,F/742/P,TRAPPIST-1e,22.0,False,0.0,4.0,0.0,0.0,1267.0,Ela Brenney,True
6141,6480_01,Earth,False,E/433/S,TRAPPIST-1e,27.0,False,352.0,14.0,1.0,407.0,15.0,Jimmya Dotsondez,False

In [45]:
df.columns

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
       'Name', 'Transported'],
      dtype='str')

In [46]:
df.info()

<class 'pandas.DataFrame'>
Index: 12970 entries, 0 to 4276
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   12970 non-null  str
 1   HomePlanet    12682 non-null  str
 2   CryoSleep     12660 non-null  object
 3   Cabin         12671 non-null  str
 4   Destination   12696 non-null  str
 5   Age           12700 non-null  float64
 6   VIP           12674 non-null  object
 7   RoomService   12707 non-null  float64
 8   FoodCourt     12681 non-null  float64
 9   ShoppingMall  12664 non-null  float64
 10  Spa           12686 non-null  float64
 11  VRDeck        12702 non-null  float64
 12  Name          12676 non-null  str
 13  Transported   12970 non-null  bool
dtypes: bool(1), float64(6), object(2), str(5)
memory usage: 1.4+ MB

In [47]:
df.isnull().sum()

PassengerId       0
HomePlanet      288
CryoSleep       310
Cabin           299
Destination     274
Age             270
VIP             296
RoomService     263
FoodCourt       289
ShoppingMall    306
Spa             284
VRDeck          268
Name            294
Transported       0
dtype: int64

In [48]:
df.describe()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,12700.000000,12707.000000,12681.000000,12664.000000,12686.000000,12702.000000
mean,28.771969,222.897852,451.961675,174.906033,308.476904,306.789482
std,14.387261,647.596664,1584.370747,590.558690,1130.279641,1180.097223
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,38.000000,49.000000,77.000000,29.000000,57.000000,42.000000
max,79.000000,14327.000000,29813.000000,23492.000000,22408.000000,24133.000000

In [49]:
df.sample(5)

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
1928,2062_01,Mars,NaN,F/398/S,TRAPPIST-1e,17.0,False,583.0,0.0,753.0,0.0,0.0,NaN,False
1979,2116_01,Earth,True,G/339/S,TRAPPIST-1e,35.0,False,0.0,0.0,0.0,0.0,0.0,Dellie Waderoachez,False
1929,4136_01,Europa,True,A/49/S,55 Cancri e,25.0,False,0.0,0.0,0.0,NaN,0.0,Alyaton Dedentive,False
1508,3246_01,Earth,False,F/612/S,TRAPPIST-1e,17.0,False,0.0,880.0,0.0,0.0,44.0,Hanne Blangibson,False
6156,6493_01,Earth,True,G/1050/P,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Terald Dillips,True

In [50]:
df[['Deck', 'Num', 'Side']] = df['Cabin'].str.split("/", expand=True)

In [51]:
df.drop(columns="Cabin", inplace=True)
df.sample(5)

,PassengerId,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,Deck,Num,Side
1596,3427_01,Earth,True,TRAPPIST-1e,53.0,False,0.0,0.0,0.0,0.0,0.0,Marine Harperez,False,G,550,S
851,0915_01,Earth,False,TRAPPIST-1e,20.0,False,157.0,0.0,0.0,544.0,3.0,Jerrye Leodger,False,G,138,S
1397,1463_01,Earth,False,PSO J318.5-22,23.0,False,200.0,414.0,73.0,1.0,1.0,NaN,False,F,282,S
3102,3343_01,Earth,True,55 Cancri e,47.0,False,0.0,0.0,0.0,0.0,0.0,Ollip Swanardy,False,G,532,S
1401,3002_01,Earth,False,PSO J318.5-22,21.0,False,0.0,0.0,0.0,95.0,642.0,Cellex Josesh,False,F,628,P

In [52]:
df.info()

<class 'pandas.DataFrame'>
Index: 12970 entries, 0 to 4276
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   12970 non-null  str
 1   HomePlanet    12682 non-null  str
 2   CryoSleep     12660 non-null  object
 3   Destination   12696 non-null  str
 4   Age           12700 non-null  float64
 5   VIP           12674 non-null  object
 6   RoomService   12707 non-null  float64
 7   FoodCourt     12681 non-null  float64
 8   ShoppingMall  12664 non-null  float64
 9   Spa           12686 non-null  float64
 10  VRDeck        12702 non-null  float64
 11  Name          12676 non-null  str
 12  Transported   12970 non-null  bool
 13  Deck          12671 non-null  str
 14  Num           12671 non-null  str
 15  Side          12671 non-null  str
dtypes: bool(1), float64(6), object(2), str(7)
memory usage: 1.6+ MB

In [53]:
imputer = KNNImputer(n_neighbors=5, weights="distance")
num_cols = df[["Age", "RoomService", "FoodCourt", "ShoppingMall", "Spa","VRDeck"]]
filled_data = imputer.fit_transform(num_cols)

In [54]:
filled_data = pd.DataFrame(filled_data, columns=num_cols.columns, index=num_cols.index)
filled_data

            Age  RoomService  FoodCourt  ShoppingMall     Spa  VRDeck
0     39.000000          0.0        0.0           0.0     0.0     0.0
1     24.000000        109.0        9.0          25.0   549.0    44.0
2     58.000000         43.0     3576.0           0.0  6715.0    49.0
3     33.000000          0.0     1283.0         371.0  3329.0   193.0
4     16.000000        303.0       70.0         151.0   565.0     2.0
...         ...          ...        ...           ...     ...     ...
4272  34.000000          0.0        0.0           0.0     0.0     0.0
4273  42.000000          0.0      847.0          17.0    10.0   144.0
4274  35.200000          0.0        0.0           0.0     0.0     0.0
4275  23.666667          0.0     2680.0           0.0     0.0   523.0
4276  43.000000          0.0        0.0           0.0     0.0     0.0

[12970 rows x 6 columns]

In [55]:
df[num_cols.columns] = filled_data

In [56]:
df.isna().sum()

PassengerId       0
HomePlanet      288
CryoSleep       310
Destination     274
Age               0
VIP             296
RoomService       0
FoodCourt         0
ShoppingMall      0
Spa               0
VRDeck            0
Name            294
Transported       0
Deck            299
Num             299
Side            299
dtype: int64

In [57]:
df.sample(10)

,PassengerId,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,Deck,Num,Side
985,2039_02,Mars,True,TRAPPIST-1e,19.0,False,0.0,0.0,0.0,0.0,0.0,Callix Jaff,False,F,405,P
4018,4292_01,Europa,False,55 Cancri e,28.0,False,0.0,31.0,0.0,1283.0,871.0,Hadiram Disight,True,A,52,S
680,1373_01,Earth,False,TRAPPIST-1e,25.0,False,2.0,145.0,830.0,14.0,1.0,Nelsie Woody,False,E,103,S
4088,4364_01,Earth,True,PSO J318.5-22,25.0,False,0.0,0.0,0.0,0.0,0.0,Dixiel Dawsoncis,True,G,720,P
163,0188_01,Earth,True,TRAPPIST-1e,56.0,False,0.0,0.0,0.0,0.0,0.0,Branda Romez,True,G,31,S
771,1566_01,Europa,True,55 Cancri e,38.0,False,0.0,0.0,0.0,0.0,0.0,Props Sloweber,False,B,52,P
1725,1833_01,Europa,False,55 Cancri e,48.0,False,140.0,127.0,0.0,4102.0,521.0,Mirark Scoudelle,False,C,61,P
3667,3938_03,Mars,True,TRAPPIST-1e,12.0,False,0.0,0.0,0.0,0.0,0.0,Gut Flité,True,F,743,S
8593,9173_01,Earth,False,PSO J318.5-22,33.0,False,0.0,688.0,2.0,0.0,426.0,Anda Cartez,False,F,1876,P
715,1471_05,Earth,True,TRAPPIST-1e,8.0,False,0.0,0.0,0.0,0.0,0.0,Kentha Morez,False,G,226,S

In [58]:
df["Name"] = df["Name"].fillna('U')

In [59]:
df.info()

<class 'pandas.DataFrame'>
Index: 12970 entries, 0 to 4276
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   12970 non-null  str
 1   HomePlanet    12682 non-null  str
 2   CryoSleep     12660 non-null  object
 3   Destination   12696 non-null  str
 4   Age           12970 non-null  float64
 5   VIP           12674 non-null  object
 6   RoomService   12970 non-null  float64
 7   FoodCourt     12970 non-null  float64
 8   ShoppingMall  12970 non-null  float64
 9   Spa           12970 non-null  float64
 10  VRDeck        12970 non-null  float64
 11  Name          12970 non-null  str
 12  Transported   12970 non-null  bool
 13  Deck          12671 non-null  str
 14  Num           12671 non-null  str
 15  Side          12671 non-null  str
dtypes: bool(1), float64(6), object(2), str(7)
memory usage: 1.6+ MB

In [60]:
df['CryoSleep'].value_counts()

CryoSleep
False    8079
True     4581
Name: count, dtype: int64

In [61]:
df['Destination'].value_counts()

Destination
TRAPPIST-1e      8871
55 Cancri e      2641
PSO J318.5-22    1184
Name: count, dtype: int64

In [62]:
df['HomePlanet'].value_counts()

HomePlanet
Earth     6865
Europa    3133
Mars      2684
Name: count, dtype: int64

In [63]:
df["VIP"].value_counts()

VIP
False    12401
True       273
Name: count, dtype: int64

In [64]:
df["VIP"] = df["VIP"].fillna(False)

In [65]:
df.isna().sum()

PassengerId       0
HomePlanet      288
CryoSleep       310
Destination     274
Age               0
VIP               0
RoomService       0
FoodCourt         0
ShoppingMall      0
Spa               0
VRDeck            0
Name              0
Transported       0
Deck            299
Num             299
Side            299
dtype: int64

In [66]:
df['CryoSleep'].value_counts()

CryoSleep
False    8079
True     4581
Name: count, dtype: int64

In [67]:
df.columns

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Destination', 'Age', 'VIP',
       'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck', 'Name',
       'Transported', 'Deck', 'Num', 'Side'],
      dtype='str')

In [68]:
spend_cols = ['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']
df["CryoSleep"] = df["CryoSleep"].fillna(
    (df[spend_cols].sum(axis=1) == 0)
)

In [69]:
df['Deck'].value_counts(), df['Num'].value_counts(), df['Side'].value_counts()

(Deck
 F    4239
 G    3781
 E    1323
 B    1141
 C    1102
 D     720
 A     354
 T      11
 Name: count, dtype: int64,
 Num
 82      34
 4       28
 56      28
 31      27
 95      27
         ..
 1882     1
 1883     1
 1885     1
 1887     1
 1890     1
 Name: count, Length: 1894, dtype: int64,
 Side
 S    6381
 P    6290
 Name: count, dtype: int64)

In [70]:
df.info()

<class 'pandas.DataFrame'>
Index: 12970 entries, 0 to 4276
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   12970 non-null  str
 1   HomePlanet    12682 non-null  str
 2   CryoSleep     12970 non-null  object
 3   Destination   12696 non-null  str
 4   Age           12970 non-null  float64
 5   VIP           12970 non-null  object
 6   RoomService   12970 non-null  float64
 7   FoodCourt     12970 non-null  float64
 8   ShoppingMall  12970 non-null  float64
 9   Spa           12970 non-null  float64
 10  VRDeck        12970 non-null  float64
 11  Name          12970 non-null  str
 12  Transported   12970 non-null  bool
 13  Deck          12671 non-null  str
 14  Num           12671 non-null  str
 15  Side          12671 non-null  str
dtypes: bool(1), float64(6), object(2), str(7)
memory usage: 1.6+ MB

In [71]:
df['Group'] = df["PassengerId"].str.split("_").str[0]

In [72]:
df["Group"].value_counts()

Group
0984    8
4005    8
4256    8
4498    8
5133    8
       ..
9265    1
9269    1
9271    1
9273    1
9277    1
Name: count, Length: 9280, dtype: int64

In [73]:
df.isna().sum()

PassengerId       0
HomePlanet      288
CryoSleep         0
Destination     274
Age               0
VIP               0
RoomService       0
FoodCourt         0
ShoppingMall      0
Spa               0
VRDeck            0
Name              0
Transported       0
Deck            299
Num             299
Side            299
Group             0
dtype: int64

In [74]:
df['Deck'] = df.groupby("Group")['Deck'].transform(
    lambda x : x.fillna(x.mode().iloc[0] if not x.mode().empty else np.nan)
)

In [75]:
df['Deck'] = df["Deck"].fillna(df["Deck"].mode()[0])
df["Side"] = df["Side"].fillna(df["Side"].mode()[0])

In [76]:
df.drop(columns='Num', inplace=True)

In [77]:
df['HomePlanet'] = df.groupby(["Group", "Deck", "Side"])["HomePlanet"].transform(
    lambda x:x.fillna(
        x.mode().iloc[0] if not x.mode().empty else np.nan
        ))

In [78]:
df["HomePlanet"] = df["HomePlanet"].fillna(df["HomePlanet"].mode()[0])

In [79]:
df["Destination"] = df.groupby(["Group", "HomePlanet"])["Destination"].transform(
    lambda x : x.fillna(x.mode().iloc[0] if not x.mode().empty else np.nan)
)

In [80]:
df["Destination"] = df["Destination"].fillna(df["Destination"].mode()[0])

In [81]:
df.isna().sum()

PassengerId     0
HomePlanet      0
CryoSleep       0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Name            0
Transported     0
Deck            0
Side            0
Group           0
dtype: int64

In [96]:
spend_cols = ['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']
df["Spendings"] = df[spend_cols].sum(axis=1)
df.drop(columns=spend_cols, inplace=True)

KeyError: "None of [Index(['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck'], dtype='str')] are in the [columns]"

In [97]:
df.to_csv("data/cleaned_combined.csv", index=False)