In [115]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer

In [116]:
df_train = pd.read_csv('data/train.csv')
df_test = pd.read_csv("data/test.csv")

df_test["Transported"] = False
df = pd.concat([df_train, df_test])
df.sample(5)

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
2339,2519_01,Earth,False,F/485/S,TRAPPIST-1e,24.0,False,172.0,775.0,344.0,0.0,0.0,Lyde Whitez,True
5812,6149_01,Earth,NaN,G/995/S,TRAPPIST-1e,15.0,False,1682.0,103.0,0.0,0.0,3.0,Card Gallencis,True
4186,4466_01,Europa,False,A/40/P,55 Cancri e,31.0,True,0.0,2461.0,0.0,51.0,2141.0,Ainkard Crakete,False
954,1990_01,Mars,True,F/395/P,TRAPPIST-1e,31.0,False,0.0,0.0,0.0,0.0,0.0,Cers Blake,False
3400,7421_02,Earth,False,F/1537/P,PSO J318.5-22,22.0,False,0.0,796.0,0.0,0.0,0.0,Kenda Fowlesterez,False

In [117]:
df.columns

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
       'Name', 'Transported'],
      dtype='str')

In [118]:
df.info()

<class 'pandas.DataFrame'>
Index: 12970 entries, 0 to 4276
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   12970 non-null  str
 1   HomePlanet    12682 non-null  str
 2   CryoSleep     12660 non-null  object
 3   Cabin         12671 non-null  str
 4   Destination   12696 non-null  str
 5   Age           12700 non-null  float64
 6   VIP           12674 non-null  object
 7   RoomService   12707 non-null  float64
 8   FoodCourt     12681 non-null  float64
 9   ShoppingMall  12664 non-null  float64
 10  Spa           12686 non-null  float64
 11  VRDeck        12702 non-null  float64
 12  Name          12676 non-null  str
 13  Transported   12970 non-null  bool
dtypes: bool(1), float64(6), object(2), str(5)
memory usage: 1.4+ MB

In [119]:
df.isnull().sum()

PassengerId       0
HomePlanet      288
CryoSleep       310
Cabin           299
Destination     274
Age             270
VIP             296
RoomService     263
FoodCourt       289
ShoppingMall    306
Spa             284
VRDeck          268
Name            294
Transported       0
dtype: int64

In [120]:
df.describe()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,12700.000000,12707.000000,12681.000000,12664.000000,12686.000000,12702.000000
mean,28.771969,222.897852,451.961675,174.906033,308.476904,306.789482
std,14.387261,647.596664,1584.370747,590.558690,1130.279641,1180.097223
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,38.000000,49.000000,77.000000,29.000000,57.000000,42.000000
max,79.000000,14327.000000,29813.000000,23492.000000,22408.000000,24133.000000

In [121]:
df.sample(5)

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
6057,6405_02,Earth,NaN,NaN,NaN,2.0,False,0.0,0.0,0.0,0.0,0.0,Feline Toddleton,True
7005,7450_01,Earth,False,G/1205/P,TRAPPIST-1e,23.0,False,509.0,0.0,193.0,0.0,2.0,Armene Sykess,False
2122,4598_01,Mars,False,E/288/P,TRAPPIST-1e,47.0,False,1294.0,0.0,5.0,0.0,0.0,Gieses Wala,False
1145,1211_05,Earth,False,F/232/S,55 Cancri e,13.0,False,1.0,212.0,843.0,78.0,10.0,Scotty Alvasquez,True
2492,5428_02,Earth,True,NaN,TRAPPIST-1e,16.0,False,0.0,0.0,0.0,0.0,0.0,Loria Huntt,False

In [122]:
df[['Deck', 'Num', 'Side']] = df['Cabin'].str.split("/", expand=True)

In [123]:
df.drop(columns="Cabin", inplace=True)
df.sample(5)

,PassengerId,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,Deck,Num,Side
8522,9097_01,Mars,True,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0,Hon Mille,True,F,1863,P
4386,4661_06,Earth,True,TRAPPIST-1e,5.0,False,0.0,0.0,0.0,NaN,0.0,Idace Moodman,False,G,757,P
3294,3539_01,Earth,False,TRAPPIST-1e,31.0,False,1.0,110.0,274.0,27.0,376.0,Olly Edwartizman,False,E,239,S
3891,4172_03,NaN,True,TRAPPIST-1e,36.0,False,0.0,0.0,0.0,0.0,0.0,Chrets Flell,True,F,856,P
5070,5416_03,Mars,True,TRAPPIST-1e,18.0,False,0.0,0.0,0.0,0.0,0.0,Ech Saf,True,F,1114,P

In [124]:
df.info()

<class 'pandas.DataFrame'>
Index: 12970 entries, 0 to 4276
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   12970 non-null  str
 1   HomePlanet    12682 non-null  str
 2   CryoSleep     12660 non-null  object
 3   Destination   12696 non-null  str
 4   Age           12700 non-null  float64
 5   VIP           12674 non-null  object
 6   RoomService   12707 non-null  float64
 7   FoodCourt     12681 non-null  float64
 8   ShoppingMall  12664 non-null  float64
 9   Spa           12686 non-null  float64
 10  VRDeck        12702 non-null  float64
 11  Name          12676 non-null  str
 12  Transported   12970 non-null  bool
 13  Deck          12671 non-null  str
 14  Num           12671 non-null  str
 15  Side          12671 non-null  str
dtypes: bool(1), float64(6), object(2), str(7)
memory usage: 1.6+ MB

In [125]:
imputer = KNNImputer(n_neighbors=5, weights="distance")
num_cols = df[["Age", "RoomService", "FoodCourt", "ShoppingMall", "Spa","VRDeck"]]
filled_data = imputer.fit_transform(num_cols)

In [126]:
filled_data = pd.DataFrame(filled_data, columns=num_cols.columns, index=num_cols.index)
filled_data

            Age  RoomService  FoodCourt  ShoppingMall     Spa  VRDeck
0     39.000000          0.0        0.0           0.0     0.0     0.0
1     24.000000        109.0        9.0          25.0   549.0    44.0
2     58.000000         43.0     3576.0           0.0  6715.0    49.0
3     33.000000          0.0     1283.0         371.0  3329.0   193.0
4     16.000000        303.0       70.0         151.0   565.0     2.0
...         ...          ...        ...           ...     ...     ...
4272  34.000000          0.0        0.0           0.0     0.0     0.0
4273  42.000000          0.0      847.0          17.0    10.0   144.0
4274  35.200000          0.0        0.0           0.0     0.0     0.0
4275  23.666667          0.0     2680.0           0.0     0.0   523.0
4276  43.000000          0.0        0.0           0.0     0.0     0.0

[12970 rows x 6 columns]

In [127]:
df[num_cols.columns] = filled_data

In [128]:
df.isna().sum()

PassengerId       0
HomePlanet      288
CryoSleep       310
Destination     274
Age               0
VIP             296
RoomService       0
FoodCourt         0
ShoppingMall      0
Spa               0
VRDeck            0
Name            294
Transported       0
Deck            299
Num             299
Side            299
dtype: int64

In [129]:
df.sample(10)

,PassengerId,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,Deck,Num,Side
3653,7959_01,Earth,False,55 Cancri e,30.0,False,0.0,683.0,547.0,46.0,14.0,Hene Daughttley,False,F,1647,P
4210,9143_01,Earth,False,TRAPPIST-1e,28.0,False,97.0,0.0,0.0,0.0,1720.0,Joelan Ricklaney,False,G,1472,S
8294,8860_01,Mars,True,TRAPPIST-1e,20.0,False,0.0,0.0,0.0,0.0,0.0,Turs Mity,True,F,1825,P
3466,7556_03,Europa,False,TRAPPIST-1e,33.0,False,0.0,673.0,0.0,0.0,783.0,Cella Mosteraked,False,NaN,NaN,NaN
354,0751_01,Mars,True,TRAPPIST-1e,21.0,False,0.0,0.0,0.0,0.0,0.0,Ray Mity,False,F,141,S
2936,3184_02,Europa,True,55 Cancri e,34.0,False,0.0,0.0,0.0,0.0,0.0,Tarmus Sechausive,True,B,117,S
4304,4591_01,Europa,True,55 Cancri e,34.0,False,0.0,0.0,0.0,0.0,0.0,Hadyon Coictrazy,True,E,287,P
1011,2079_03,Earth,False,TRAPPIST-1e,16.0,False,32.0,9.0,0.0,0.0,1408.0,Phia Pierry,False,F,406,S
2393,5222_01,Earth,True,TRAPPIST-1e,50.0,False,0.0,0.0,0.0,0.0,0.0,Delody Dunnisey,False,G,847,S
3448,7530_03,Europa,NaN,TRAPPIST-1e,38.0,False,0.0,1222.0,0.0,734.0,3153.0,Mirfar Underative,False,B,285,S

In [130]:
df["Name"] = df["Name"].fillna('U')

In [131]:
df.info()

<class 'pandas.DataFrame'>
Index: 12970 entries, 0 to 4276
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   12970 non-null  str
 1   HomePlanet    12682 non-null  str
 2   CryoSleep     12660 non-null  object
 3   Destination   12696 non-null  str
 4   Age           12970 non-null  float64
 5   VIP           12674 non-null  object
 6   RoomService   12970 non-null  float64
 7   FoodCourt     12970 non-null  float64
 8   ShoppingMall  12970 non-null  float64
 9   Spa           12970 non-null  float64
 10  VRDeck        12970 non-null  float64
 11  Name          12970 non-null  str
 12  Transported   12970 non-null  bool
 13  Deck          12671 non-null  str
 14  Num           12671 non-null  str
 15  Side          12671 non-null  str
dtypes: bool(1), float64(6), object(2), str(7)
memory usage: 1.6+ MB

In [132]:
df['CryoSleep'].value_counts()

CryoSleep
False    8079
True     4581
Name: count, dtype: int64

In [133]:
df['Destination'].value_counts()

Destination
TRAPPIST-1e      8871
55 Cancri e      2641
PSO J318.5-22    1184
Name: count, dtype: int64

In [134]:
df['HomePlanet'].value_counts()

HomePlanet
Earth     6865
Europa    3133
Mars      2684
Name: count, dtype: int64

In [135]:
df["VIP"].value_counts()

VIP
False    12401
True       273
Name: count, dtype: int64

In [136]:
df["VIP"] = df["VIP"].fillna(False)

In [137]:
df.isna().sum()

PassengerId       0
HomePlanet      288
CryoSleep       310
Destination     274
Age               0
VIP               0
RoomService       0
FoodCourt         0
ShoppingMall      0
Spa               0
VRDeck            0
Name              0
Transported       0
Deck            299
Num             299
Side            299
dtype: int64

In [138]:
df['CryoSleep'].value_counts()

CryoSleep
False    8079
True     4581
Name: count, dtype: int64

In [139]:
df.columns

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Destination', 'Age', 'VIP',
       'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck', 'Name',
       'Transported', 'Deck', 'Num', 'Side'],
      dtype='str')

In [140]:
spend_cols = ['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']
df["CryoSleep"] = df["CryoSleep"].fillna(
    (df[spend_cols].sum(axis=1) == 0)
)

In [141]:
df['Deck'].value_counts(), df['Num'].value_counts(), df['Side'].value_counts()

(Deck
 F    4239
 G    3781
 E    1323
 B    1141
 C    1102
 D     720
 A     354
 T      11
 Name: count, dtype: int64,
 Num
 82      34
 4       28
 56      28
 31      27
 95      27
         ..
 1882     1
 1883     1
 1885     1
 1887     1
 1890     1
 Name: count, Length: 1894, dtype: int64,
 Side
 S    6381
 P    6290
 Name: count, dtype: int64)

In [142]:
df.info()

<class 'pandas.DataFrame'>
Index: 12970 entries, 0 to 4276
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   12970 non-null  str
 1   HomePlanet    12682 non-null  str
 2   CryoSleep     12970 non-null  object
 3   Destination   12696 non-null  str
 4   Age           12970 non-null  float64
 5   VIP           12970 non-null  object
 6   RoomService   12970 non-null  float64
 7   FoodCourt     12970 non-null  float64
 8   ShoppingMall  12970 non-null  float64
 9   Spa           12970 non-null  float64
 10  VRDeck        12970 non-null  float64
 11  Name          12970 non-null  str
 12  Transported   12970 non-null  bool
 13  Deck          12671 non-null  str
 14  Num           12671 non-null  str
 15  Side          12671 non-null  str
dtypes: bool(1), float64(6), object(2), str(7)
memory usage: 1.6+ MB

In [143]:
df['Group'] = df["PassengerId"].str.split("_").str[0]

In [144]:
df["Group"].value_counts()

Group
0984    8
4005    8
4256    8
4498    8
5133    8
       ..
9265    1
9269    1
9271    1
9273    1
9277    1
Name: count, Length: 9280, dtype: int64

In [145]:
df.isna().sum()

PassengerId       0
HomePlanet      288
CryoSleep         0
Destination     274
Age               0
VIP               0
RoomService       0
FoodCourt         0
ShoppingMall      0
Spa               0
VRDeck            0
Name              0
Transported       0
Deck            299
Num             299
Side            299
Group             0
dtype: int64

In [146]:
df['Deck'] = df.groupby("Group")['Deck'].transform(
    lambda x : x.fillna(x.mode().iloc[0] if not x.mode().empty else np.nan)
)

In [147]:
df['Deck'] = df["Deck"].fillna(df["Deck"].mode()[0])
df["Side"] = df["Side"].fillna(df["Side"].mode()[0])

In [148]:
df.drop(columns='Num', inplace=True)

In [149]:
df['HomePlanet'] = df.groupby(["Group", "Deck", "Side"])["HomePlanet"].transform(
    lambda x:x.fillna(
        x.mode().iloc[0] if not x.mode().empty else np.nan
        ))

In [150]:
df["HomePlanet"] = df["HomePlanet"].fillna(df["HomePlanet"].mode()[0])

In [151]:
df["Destination"] = df.groupby(["Group", "HomePlanet"])["Destination"].transform(
    lambda x : x.fillna(x.mode().iloc[0] if not x.mode().empty else np.nan)
)

In [152]:
df["Destination"] = df["Destination"].fillna(df["Destination"].mode()[0])

In [153]:
df.isna().sum()

PassengerId     0
HomePlanet      0
CryoSleep       0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Name            0
Transported     0
Deck            0
Side            0
Group           0
dtype: int64

In [154]:
spend_cols = ['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']
df["Spendings"] = df[spend_cols].sum(axis=1)
df.drop(columns=spend_cols, inplace=True)

In [155]:
df.info()

<class 'pandas.DataFrame'>
Index: 12970 entries, 0 to 4276
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  12970 non-null  str
 1   HomePlanet   12970 non-null  str
 2   CryoSleep    12970 non-null  object
 3   Destination  12970 non-null  str
 4   Age          12970 non-null  float64
 5   VIP          12970 non-null  object
 6   Name         12970 non-null  str
 7   Transported  12970 non-null  bool
 8   Deck         12970 non-null  str
 9   Side         12970 non-null  str
 10  Group        12970 non-null  object
 11  Spendings    12970 non-null  float64
dtypes: bool(1), float64(2), object(3), str(6)
memory usage: 1.2+ MB

In [156]:
df["CryoSleep"] = df["CryoSleep"].astype(bool)
df["CryoSleep"] = df["CryoSleep"].astype(int)

df["VIP"] = df["VIP"].astype(bool)
df["VIP"] = df["VIP"].astype(int)

df["Transported"] = df["Transported"].astype(bool)
df["Transported"] = df["Transported"].astype(int)

In [157]:
df["Side"].value_counts()

Side
S    6680
P    6290
Name: count, dtype: int64

In [158]:
df["Side"] = df["Side"].map({
    "P" :0,
    "S" :1
})

In [159]:
df = pd.get_dummies(df, columns=["HomePlanet", "Destination", "Deck"], dtype=int)

In [160]:
df.columns

Index(['PassengerId', 'CryoSleep', 'Age', 'VIP', 'Name', 'Transported', 'Side',
       'Group', 'Spendings', 'HomePlanet_Earth', 'HomePlanet_Europa',
       'HomePlanet_Mars', 'Destination_55 Cancri e',
       'Destination_PSO J318.5-22', 'Destination_TRAPPIST-1e', 'Deck_A',
       'Deck_B', 'Deck_C', 'Deck_D', 'Deck_E', 'Deck_F', 'Deck_G', 'Deck_T'],
      dtype='str')

In [161]:
# bool_cols = df.select_dtypes(bool).columns
# df[bool_cols] = df[bool_cols].astype(int)

In [166]:
df["PassengerId"].sample(5)

390     0431_01
3854    8426_01
5200    5545_02
424     0886_02
5970    6325_02
Name: PassengerId, dtype: str

In [172]:
df["Group"] = df["Group"].astype(int)
df["GroupSize"] = df.groupby("Group")["Group"].transform("count")
df["GroupMember"] = df["PassengerId"].str.split("_").str[1]

In [176]:
cols_to_drop = ['Name', 'PassengerId']
df = df.drop(columns=cols_to_drop)

In [180]:
df.columns

Index(['CryoSleep', 'Age', 'VIP', 'Transported', 'Side', 'Group', 'Spendings',
       'HomePlanet_Earth', 'HomePlanet_Europa', 'HomePlanet_Mars',
       'Destination_55 Cancri e', 'Destination_PSO J318.5-22',
       'Destination_TRAPPIST-1e', 'Deck_A', 'Deck_B', 'Deck_C', 'Deck_D',
       'Deck_E', 'Deck_F', 'Deck_G', 'Deck_T', 'GroupSize', 'GroupMember'],
      dtype='str')

In [177]:
df.info()

<class 'pandas.DataFrame'>
Index: 12970 entries, 0 to 4276
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   CryoSleep                  12970 non-null  int64
 1   Age                        12970 non-null  float64
 2   VIP                        12970 non-null  int64
 3   Transported                12970 non-null  int64
 4   Side                       12970 non-null  int64
 5   Group                      12970 non-null  int64
 6   Spendings                  12970 non-null  float64
 7   HomePlanet_Earth           12970 non-null  int64
 8   HomePlanet_Europa          12970 non-null  int64
 9   HomePlanet_Mars            12970 non-null  int64
 10  Destination_55 Cancri e    12970 non-null  int64
 11  Destination_PSO J318.5-22  12970 non-null  int64
 12  Destination_TRAPPIST-1e    12970 non-null  int64
 13  Deck_A                     12970 non-null  int64
 14  Deck_B                     12970 non-null  int64
 15  Deck_C                     12970 non-null  int64
 16  Deck_D                     12970 non-null  int64
 17  Deck_E                     12970 non-null  int64
 18  Deck_F                     12970 non-null  int64
 19  Deck_G                     12970 non-null  int64
 20  Deck_T                     12970 non-null  int64
 21  GroupSize                  12970 non-null  int64
 22  GroupMember                12970 non-null  object
dtypes: float64(2), int64(20), object(1)
memory usage: 2.9+ MB

In [181]:
df.to_csv("data/cleaned_combined.csv", index=False)